repos:
- repo: local
  hooks:
    - id: black
      name: black
      entry: python -m black .
      language: system
      types: [python, jupyter]
    - id: pytest-check
      name: pytest-check
      entry: pytest -v --cov --cov-report term-missing
      language: system
      pass_filenames: false
      always_run: true
